# We'll use a Node image for our React app later.
# This is just a placeholder to make the build pass.
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# A command to keep the container running in dev
CMD ["tail", "-f", "/dev/null"]